services:
  db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-senhaSuper@Secreta}
      - POSTGRES_DB=${DB_DATABASE:-database}
    # extra_hosts:
    #   - host.docker.internal
    volumes:
      - volumeDatabase:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - networkName
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - ./:/var/www
    env_file:
      - .env
    networks:
      - networkName

  nginx:
    image: nginx
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - networkName

  # mailpit:
  #   image: axllent/mailpit
  #   container_name: mailpit
  #   restart: unless-stopped
  #   volumes:
  #       - ./data:/data
  #   ports:
  #       - 8025:8025
  #       - 1025:1025
  #   environment:
  #       MP_MAX_MESSAGES: 5000
  #       MP_DATABASE: /data/mailpit.db
  #       MP_SMTP_AUTH_ACCEPT_ANY: 1
  #       MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
  networkName:
    # driver: bridge

volumes:
  volumeDatabase:
